// Cross-platform end-to-end smoke runner (Windows + Linux + macOS).
//
//   node scripts/smoke.mjs                # same as `all`
//   node scripts/smoke.mjs minicloak
//   node scripts/smoke.mjs minimail
//   node scripts/smoke.mjs minibucket
//   node scripts/smoke.mjs minisuite      # all three inside one process
//   node scripts/smoke.mjs all            # every case, sequentially
//   node scripts/smoke.mjs all --no-build # skip `cargo build --release`
//
// For each service: build the release binary, start it on a dedicated smoke
// port, wait for those ports to accept a TCP connection, run the Python
// smoketest(s) against it, then kill the server — on success, on failure, and
// on Ctrl-C alike. Exits with the Python test's exit code.
//
// The `minisuite` case starts the all-in-one binary on the same smoke ports and
// then runs all three crates' smoketests against that single process, which is
// the point: the suite must be indistinguishable from the three servers.
//
// This is deliberately a Node script rather than justfile shell: the old
// per-crate `just smoke` recipes used POSIX job control (`&`, `trap`, `$!`),
// which does not exist in PowerShell.
//
// minibucket's smoketest.py hardcodes endpoint http://127.0.0.1:9123 and the
// credentials alice/alicepass, so those values are not configurable here.
// It also needs boto3:  pip install boto3

import { spawn, spawnSync } from "node:child_process";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { connect } from "node:net";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const exe = process.platform === "win32" ? ".exe" : "";
const bin = (name) => join(root, "target", "release", name + exe);
const smokeDir = (name) => join(root, "target", "smoke", name);

// Python is `python` on Windows, usually `python3` elsewhere.
const PYTHON = process.env.PYTHON ?? (process.platform === "win32" ? "python" : "python3");

const SERVICES = {
  minicloak: {
    // Port the smoke runner waits for before starting the Python test.
    port: 19500,
    args: () => [
      "--bind",
      "127.0.0.1:19500",
      "--key",
      join(root, "target", "smoke", "minicloak-key.pem"),
    ],
    test: () => [
      join(root, "crates", "minicloak", "smoketest.py"),
      "http://127.0.0.1:19500",
    ],
    // Fresh signing key per run so a stale/corrupt key cannot mask a failure.
    reset: () => rmSync(join(root, "target", "smoke", "minicloak-key.pem"), { force: true }),
  },
  minimail: {
    // The HTTP port comes up after SMTP, so waiting on it covers both.
    port: 18025,
    args: () => [
      "--smtp-bind",
      "127.0.0.1:11025",
      "--http-bind",
      "127.0.0.1:18025",
      "--root",
      smokeDir("minimail"),
    ],
    test: () => [
      join(root, "crates", "minimail", "smoketest.py"),
      "--smtp",
      "127.0.0.1:11025",
      "--http",
      "127.0.0.1:18025",
    ],
    reset: () => {
      rmSync(smokeDir("minimail"), { recursive: true, force: true });
      mkdirSync(smokeDir("minimail"), { recursive: true });
    },
  },
  minibucket: {
    // 9123 + alice/alicepass are hardcoded inside minibucket's smoketest.py.
    port: 9123,
    args: () => [
      "--bind",
      "127.0.0.1:9123",
      "--root",
      smokeDir("minibucket"),
      "--access-key",
      "alice",
      "--secret-key",
      "alicepass",
    ],
    test: () => [join(root, "crates", "minibucket", "smoketest.py")],
    reset: () => {
      rmSync(smokeDir("minibucket"), { recursive: true, force: true });
      mkdirSync(smokeDir("minibucket"), { recursive: true });
    },
  },
  // All three servers in ONE process, driven by a generated minisuite.toml.
  // The ports match the three cases above so the very same smoketests apply;
  // minibucket in particular has 9123 + alice/alicepass baked into its test.
  minisuite: {
    // Every port the suite must have open before the tests may start.
    ports: [19500, 18025, 9123, 19900],
    args: () => {
      writeFileSync(
        SUITE_TOML,
        [
          "# Generated by scripts/smoke.mjs; edits are overwritten.",
          "[minicloak]",
          'bind = "127.0.0.1:19500"',
          "[minimail]",
          'smtp_bind = "127.0.0.1:11025"',
          'http_bind = "127.0.0.1:18025"',
          "[minibucket]",
          'bind = "127.0.0.1:9123"',
          'access_key = "alice"',
          'secret_key = "alicepass"',
          "",
        ].join("\n"),
      );
      return [
        "--data",
        smokeDir("minisuite"),
        "--config",
        SUITE_TOML,
        "--landing-bind",
        "127.0.0.1:19900",
      ];
    },
    tests: () => [
      SERVICES.minicloak.test(),
      SERVICES.minimail.test(),
      SERVICES.minibucket.test(),
    ],
    // The landing page is minisuite's own contribution, so it gets its own check.
    after: async () => {
      const url = "http://127.0.0.1:19900/healthz";
      try {
        const res = await fetch(url);
        const body = await res.text();
        if (res.status !== 200) {
          console.error(`minisuite: ${url} returned ${res.status}`);
          return 1;
        }
        for (const name of ["minicloak", "minimail", "minibucket"]) {
          if (!body.includes(`"${name}"`)) {
            console.error(`minisuite: ${url} does not list ${name}: ${body}`);
            return 1;
          }
        }
        console.log(`minisuite: ${url} -> 200 ${body}`);
        return 0;
      } catch (err) {
        console.error(`minisuite: ${url}: ${err.message}`);
        return 1;
      }
    },
    reset: () => {
      rmSync(smokeDir("minisuite"), { recursive: true, force: true });
      mkdirSync(smokeDir("minisuite"), { recursive: true });
    },
  },
};

// Written fresh on every run so the suite's config can never go stale.
const SUITE_TOML = join(root, "target", "smoke", "minisuite.toml");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

/** Resolve once the TCP port accepts a connection, or reject after timeoutMs. */
async function waitForPort(port, timeoutMs = 15000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const up = await new Promise((resolve) => {
      const sock = connect({ host: "127.0.0.1", port });
      const done = (ok) => {
        sock.destroy();
        resolve(ok);
      };
      sock.setTimeout(1000);
      sock.once("connect", () => done(true));
      sock.once("timeout", () => done(false));
      sock.once("error", () => done(false));
    });
    if (up) return;
    await sleep(200);
  }
  throw new Error(`port ${port} did not open within ${timeoutMs / 1000}s`);
}

/** Run a command to completion, inheriting stdio. Returns the exit code. */
function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, {
    cwd: root,
    stdio: "inherit",
    shell: false,
    // The smoketests print unicode; a Windows console defaults to cp1252 and
    // Python would raise UnicodeEncodeError on the first non-ASCII character.
    env: { ...process.env, PYTHONIOENCODING: "utf-8" },
    ...opts,
  });
  if (r.error) {
    console.error(`error: failed to run ${cmd}: ${r.error.message}`);
    return 127;
  }
  return r.status ?? 1;
}

/** Build, launch, wait, test, kill. Returns the exit code of the Python test. */
async function smoke(name, { build }) {
  const svc = SERVICES[name];
  console.log(`\n=== ${name} ===`);

  if (build) {
    const code = run("cargo", ["build", "--release", "-p", name]);
    if (code !== 0) {
      console.error(`${name}: cargo build failed`);
      return code;
    }
  }

  mkdirSync(join(root, "target", "smoke"), { recursive: true });
  svc.reset?.();

  const args = svc.args();
  console.log(`starting: ${bin(name)} ${args.join(" ")}`);
  const server = spawn(bin(name), args, {
    cwd: root,
    stdio: ["ignore", "inherit", "inherit"],
  });

  let serverExit = null;
  server.on("exit", (code, signal) => {
    serverExit = signal ?? code;
  });

  // Kill the server no matter how we leave this function.
  let killed = false;
  const kill = () => {
    if (killed || server.exitCode !== null || serverExit !== null) return;
    killed = true;
    // On Windows there is no SIGTERM: taskkill /T tears down the whole tree.
    if (process.platform === "win32") {
      spawnSync("taskkill", ["/pid", String(server.pid), "/T", "/F"], {
        stdio: "ignore",
      });
    } else {
      server.kill("SIGTERM");
    }
  };
  const onSignal = () => {
    kill();
    process.exit(130);
  };
  process.once("SIGINT", onSignal);
  process.once("SIGTERM", onSignal);

  try {
    if (server.exitCode !== null || serverExit !== null)
      throw new Error(`${name} exited immediately (${serverExit})`);
    for (const port of svc.ports ?? [svc.port]) {
      await waitForPort(port);
      console.log(`${name} is listening on 127.0.0.1:${port}`);
    }
    for (const test of svc.tests ? svc.tests() : [svc.test()]) {
      const code = run(PYTHON, test);
      if (code !== 0) {
        console.error(`${name}: smoketest failed (exit ${code})`);
        return code;
      }
    }
    return svc.after ? await svc.after() : 0;
  } catch (err) {
    console.error(`${name}: ${err.message}`);
    return 1;
  } finally {
    kill();
    process.off("SIGINT", onSignal);
    process.off("SIGTERM", onSignal);
    // Give the OS a moment to release the port before the next service starts.
    await sleep(300);
  }
}

// --- CLI ------------------------------------------------------------------
const argv = process.argv.slice(2);
const build = !argv.includes("--no-build");
const which = argv.find((a) => !a.startsWith("-")) ?? "all";

const names = which === "all" ? Object.keys(SERVICES) : [which];
for (const n of names) {
  if (!SERVICES[n]) {
    console.error(
      `usage: node scripts/smoke.mjs [${Object.keys(SERVICES).join("|")}|all] [--no-build]`,
    );
    process.exit(1);
  }
}

const results = [];
for (const name of names) results.push([name, await smoke(name, { build })]);

if (results.length > 1) {
  console.log("\n=== summary ===");
  for (const [name, code] of results)
    console.log(`  ${code === 0 ? "PASS" : "FAIL"}  ${name}`);
}

process.exit(results.some(([, code]) => code !== 0) ? 1 : 0);
